"""Inventory engine: weighted-average costing + NXT (Nhập-Xuất-Tồn) report."""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from data.repositories.inventory_repo import InventoryRepository
from data.repositories.item_repo import ItemRepository
from domain.models.inventory import InventoryMovement, MovementKind, NxtRow
from domain.models.item import Item


class InventoryError(ValueError):
    pass


class InventoryService:
    """All stock state derives from the movement ledger.

    OUT movements are costed at the running weighted average at the moment they
    are recorded (``record_out``); that cost is then stored, so reports are a
    straight aggregation of the ledger.
    """

    def __init__(
        self,
        repo: InventoryRepository,
        item_repo: ItemRepository | None = None,
    ) -> None:
        self._repo = repo
        self._items = item_repo or ItemRepository()

    # ----- recording -------------------------------------------------------

    def record_in(
        self,
        item_code: str,
        quantity: Decimal,
        unit_cost: Decimal,
        *,
        move_date: date | None = None,
        kind: MovementKind = MovementKind.IN,
        source_ref: str = "",
        note: str = "",
        account_code: str = "",
        item_name: str = "",
        unit: str = "",
    ) -> InventoryMovement:
        if kind is MovementKind.OUT:
            raise InventoryError("record_in không nhận bút toán xuất kho.")
        if quantity <= 0:
            raise InventoryError("Số lượng nhập phải lớn hơn 0.")
        if unit_cost < 0:
            raise InventoryError("Đơn giá nhập không được âm.")
        item = self._items.find_by_code(item_code)
        movement = InventoryMovement(
            item_code=item_code,
            # Tên hàng lấy từ danh mục; nếu mặt hàng chưa khai báo thì dùng tên
            # ghi trên chứng từ (vd: mua NVL mới chưa có trong Danh mục).
            item_name=(item.name if item else "") or item_name,
            # ĐVT trên chứng từ THẮNG (kế toán nhập "kg" phải giữ "kg"); rỗng →
            # mới lấy ĐVT danh mục. Ngược chiều ưu tiên với tên vì danh mục hay
            # để ĐVT mặc định "Cái" đè lên ĐVT thật của hàng.
            unit=unit or (item.unit if item else ""),
            # Mã kho (TK kho) chọn trên chứng từ thắng; rỗng → theo mặt hàng.
            account_code=account_code or (item.account_code if item else ""),
            move_date=move_date or date.today(),
            kind=kind,
            quantity=quantity,
            unit_cost=unit_cost,
            source_ref=source_ref,
            note=note,
            created_at=datetime.now(),
        )
        return self._repo.insert(movement)

    def record_out(
        self,
        item_code: str,
        quantity: Decimal,
        *,
        move_date: date | None = None,
        source_ref: str = "",
        note: str = "",
        allow_negative: bool = True,
        account_code: str = "",
        item_name: str = "",
        unit: str = "",
    ) -> InventoryMovement:
        if quantity <= 0:
            raise InventoryError("Số lượng xuất phải lớn hơn 0.")
        # Một lượt quét sổ cho cả tồn lẫn giá bình quân (trước đây on_hand +
        # average_cost quét 3 lần cho mỗi lần xuất).
        on_hand, value = self._aggregate(item_code)
        if not allow_negative and quantity > on_hand:
            raise InventoryError(
                f"Không đủ tồn kho cho '{item_code}': cần {quantity}, còn {on_hand}."
            )
        unit_cost = (value / on_hand).quantize(Decimal("1")) if on_hand > 0 else Decimal("0")
        item = self._items.find_by_code(item_code)
        movement = InventoryMovement(
            item_code=item_code,
            # Tên hàng lấy từ danh mục; nếu mặt hàng chưa khai báo thì dùng tên
            # ghi trên chứng từ (vd: bán hàng mặt hàng chưa có trong Danh mục).
            item_name=(item.name if item else "") or item_name,
            unit=unit or (item.unit if item else ""),
            # Mã kho (TK kho) chọn trên chứng từ thắng; rỗng → theo mặt hàng.
            account_code=account_code or (item.account_code if item else ""),
            move_date=move_date or date.today(),
            kind=MovementKind.OUT,
            quantity=quantity,
            unit_cost=unit_cost,
            source_ref=source_ref,
            note=note,
            created_at=datetime.now(),
        )
        return self._repo.insert(movement)

    def remove_source(self, source_ref: str) -> None:
        """Drop every movement generated by a source document (vd: hủy hóa đơn)."""
        if source_ref:
            self._repo.delete_by_source(source_ref)

    def remove_items(self, item_codes: list[str]) -> int:
        """Xóa hẳn một/nhiều mặt hàng khỏi kho: bỏ mọi bút toán nhập–xuất của các
        mã đó nên chúng không còn xuất hiện trong sổ NXT. Trả số dòng đã xóa."""
        return self._repo.delete_by_items(item_codes)

    def replace_source_movements(
        self, source_ref: str, movements: list[InventoryMovement]
    ) -> None:
        """Idempotently set all movements tagged with ``source_ref``.

        Deletes the source's existing movements then re-inserts the supplied
        list. Used by worksheets that own a fixed source key (vd: Bảng kê NVL
        chính → ``BK-NVL:<kỳ>``) so re-saving refreshes rather than stacks.
        """
        self._repo.delete_by_source(source_ref)
        for movement in movements:
            self._repo.insert(movement)

    # ----- stock queries ---------------------------------------------------

    def _aggregate(self, item_code: str) -> tuple[Decimal, Decimal]:
        """Tồn (số lượng) và giá trị tồn trong một lượt quét sổ duy nhất."""
        qty = Decimal("0")
        value = Decimal("0")
        for m in self._repo.list_for_item(item_code):
            qty += m.signed_quantity
            value += m.signed_value
        return qty, value

    def on_hand(self, item_code: str) -> Decimal:
        return self._aggregate(item_code)[0]

    def stock_value(self, item_code: str) -> Decimal:
        return self._aggregate(item_code)[1]

    def average_cost(self, item_code: str) -> Decimal:
        qty, value = self._aggregate(item_code)
        if qty <= 0:
            return Decimal("0")
        return (value / qty).quantize(Decimal("1"))

    def reprice_in(
        self,
        item_code: str,
        unit_cost: Decimal,
        *,
        date_from: date,
        date_to: date,
        account_code: str = "",
    ) -> int:
        """Đặt lại đơn giá cho các bút toán NHẬP của một mặt hàng trong kỳ.

        Chỉ sửa đơn giá trên bút toán đã có — **không** tạo thêm lượng nhập. Dùng
        khi bảng giá thành đẩy giá thành đơn vị ngược về kho thành phẩm: số lượng
        do chứng từ nhập kho quyết định, giá do bảng giá thành quyết định.

        Bỏ qua tồn đầu kỳ (``OPENING``): đó là số dư mang sang, không phải hàng
        sản xuất trong kỳ. Trả về số bút toán đã đổi giá.
        """
        changed = 0
        for m in self._repo.list_all():
            if m.item_code != item_code or m.kind is not MovementKind.IN:
                continue
            if not (date_from <= m.move_date <= date_to):
                continue
            if account_code and m.account_code != account_code:
                continue
            if m.id is None or m.unit_cost == unit_cost:
                continue
            self._repo.update_cost(m.id, unit_cost)
            changed += 1
        return changed

    # ----- NXT report ------------------------------------------------------

    def compute_nxt(
        self,
        date_from: date | None = None,
        date_to: date | None = None,
        *,
        exclude_source_prefix: str | tuple[str, ...] | None = None,
    ) -> list[NxtRow]:
        """Per-item Opening / In / Out / Closing over an optional date window.

        ``exclude_source_prefix`` drops movements whose ``source_ref`` starts with
        it — used to read the *real* (document-driven) picture while ignoring
        movements a worksheet itself pushed, so the two never double-count. Pass a
        tuple to exclude several sources at once (vd: cả Bảng kê NVL lẫn phần
        xuất NVL theo giá thành).
        """
        units = {i.code: i.unit for i in self._items.list_all()}
        rows: dict[str, NxtRow] = {}
        for m in self._repo.list_all():
            if exclude_source_prefix and m.source_ref.startswith(exclude_source_prefix):
                continue
            row = rows.get(m.item_code)
            if row is None:
                row = NxtRow(
                    item_code=m.item_code,
                    item_name=m.item_name,
                    # ĐVT thật trên chứng từ ưu tiên; rỗng mới lấy từ danh mục.
                    unit=m.unit or units.get(m.item_code, ""),
                    account_code=m.account_code,
                )
                rows[m.item_code] = row
            elif not row.unit and m.unit:
                row.unit = m.unit
            if date_from and m.move_date < date_from:
                row.opening_qty += m.signed_quantity
                row.opening_value += m.signed_value
            elif date_to and m.move_date > date_to:
                continue
            elif m.kind.is_inbound:
                row.in_qty += m.quantity
                row.in_value += m.value
            else:
                row.out_qty += m.quantity
                row.out_value += m.value
        # Bỏ dòng rỗng hoàn toàn: mặt hàng chỉ có phát sinh sau date_to bị loại
        # hết ở trên nên còn lại toàn 0 — không nên hiện trong báo cáo NXT.
        visible = [
            r for r in rows.values()
            if r.opening_qty or r.opening_value
            or r.in_qty or r.in_value or r.out_qty or r.out_value
        ]
        return sorted(visible, key=lambda r: r.item_code)

    def list_stock_materials(
        self, account_prefix: str = "152"
    ) -> list[tuple[str, str, str]]:
        """(mã, tên, ĐVT) duy nhất của mặt hàng trong sổ kho theo nhóm TK.

        Nguồn là **sổ kho ledger** (chứng từ nhập–xuất, đúng như tab Nhập–Xuất–Tồn),
        không phải bảng kê nhập tay. Dùng để đồng bộ NVL đã phát sinh trong kho
        sang Danh mục vật tư (mặc định lọc nhóm 152 — nguyên vật liệu).
        """
        seen: dict[str, tuple[str, str]] = {}
        for r in self.compute_nxt():
            if r.account_code.startswith(account_prefix):
                seen[r.item_code] = (r.item_name, r.unit)
        return [(code, name, unit) for code, (name, unit) in sorted(seen.items())]
